extends: "@istanbuljs/nyc-config-typescript"
all: true
cache: false
check-coverage: true
include:
  - "src/**/*.ts"
  - "out/**/*.js"
exclude:
  - "**/test/*"
reporter:
  - "text-summary"
  - "lcov"
  - "html"
require:
  - "ts-node/register"
sourceMap: true
