export const icons = {
	unfold:                               { label: "$(unfold)",                                  description: "unfold" },
	ungroupByRefType:                     { label: "$(ungroup-by-ref-type)",                     description: "ungroup-by-ref-type" },
	unlock:                               { label: "$(unlock)",                                  description: "unlock" },
	unmute:                               { label: "$(unmute)",                                  description: "unmute" },
	unverified:                           { label: "$(unverified)",                              description: "unverified" },
	variable:                             { label: "$(variable)",                                description: "variable" },
	verified:                             { label: "$(verified)",                                description: "verified" },
	versions:                             { label: "$(versions)",                                description: "versions" },
	vm:                                   { label: "$(vm)",                                      description: "vm" },
	vmActive:                             { label: "$(vm-active)",                               description: "vm-active" },
	vmConnect:                            { label: "$(vm-connect)",                              description: "vm-connect" },
	vmOutline:                            { label: "$(vm-outline)",                              description: "vm-outline" },
	vmRunning:                            { label: "$(vm-running)",                              description: "vm-running" },
	warning:                              { label: "$(warning)",                                 description: "warning" },
	watch:                                { label: "$(watch)",                                   description: "watch" },
	whitespace:                           { label: "$(whitespace)",                              description: "whitespace" },
	wholeWord:                            { label: "$(whole-word)",                              description: "whole-word" },
	window:                               { label: "$(window)",                                  description: "window" },
	wordWrap:                             { label: "$(word-wrap)",                               description: "word-wrap" },
	wrench:                               { label: "$(wrench)",                                  description: "wrench" },
	wrenchSubaction:                      { label: "$(wrench-subaction)",                        description: "wrench-subaction" },
	x:                                    { label: "$(x)",                                       description: "x" },
	zap:                                  { label: "$(zap)",                                     description: "zap" },
	zoomIn:                               { label: "$(zoom-in)",                                 description: "zoom-in" },
	zoomOut:                              { label: "$(zoom-out)",                                description: "zoom-out" },
}
