name: Wallpaper Setting CI

on:
  push:

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install Node.js
      uses: actions/setup-node@master
      with:
        node-version: 14
    - run: npm install -g yarn
    - run: yarn install
    - run: yarn compile
    - run: xvfb-run -a yarn test
      if: runner.os == 'Linux'
    - run: yarn test
      if: runner.os != 'Linux'
  coverage:
    needs: [ test ]
    name: coverage
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install Node.js
      uses: actions/setup-node@master
      with:
        node-version: 14
    - run: npm install -g yarn
    - run: yarn install
    - run: yarn compile
    - run: xvfb-run -a yarn coverage
    - uses: paambaati/codeclimate-action@v2.7.5
      env:
        CC_TEST_REPORTER_ID: a7202a1a6a2fc73bfb3e9d8b616b983b0281a02cca3e0b030b9d6482af3f1c25
      with:
        coverageLocations: ${{github.workspace}}/coverage/lcov.info:lcov
